"""
Tests for P2-011B read-only Coinbase fill response discovery script.

All tests are pure and require no broker, no .env, no network.
"""

import re
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path("scripts/coinbase_fill_response_discovery.py")
REPORT = Path("docs/COINBASE_FILL_RESPONSE_DISCOVERY.md")


def test_script_runs_and_produces_report():
    """The script must execute cleanly when run as a file and write the report."""
    repo_root = Path(__file__).resolve().parents[1]
    script_path = repo_root / "scripts" / "coinbase_fill_response_discovery.py"

    result = subprocess.run(
        [sys.executable, str(script_path)],
        cwd=repo_root,
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, f"stderr: {result.stderr}\nstdout: {result.stdout}"
    assert "Wrote" in result.stdout, result.stdout


def test_report_contains_all_seven_answers():
    """After running, the report must contain answers to all 7 gating questions."""
    # We assume the report was generated by a prior run in CI or by the developer.
    # For unit test we check the committed/generated content if present, or skip gracefully.
    if not REPORT.exists():
        pytest.skip("Report not present in this checkout (generated on demand)")

    content = REPORT.read_text(encoding="utf-8")

    assert "1. Which Coinbase response currently contains actual fill" in content
    assert "2. Are average_filled_price, filled_size" in content
    assert "3. Can sell proceeds be captured directly" in content
    assert "4. Are partial fills possible" in content
    assert "5. Could repeated get_order_status polling duplicate rows" in content
    assert "6. Which exact function is the safest future hook" in content
    assert "7. What tests are required before a future hook patch" in content

    # Key evidence assertions (these must remain true for the discovery to be valid)
    assert "broker_coinbase.py:get_order_status" in content
    assert "position_manager.py" in content
    assert "No" in content and "sell proceeds" in content.lower()
    assert "HIGH" in content and "duplicate" in content.lower()
    assert "exactly once per unique order_id" in content


def test_discovery_script_is_pure_read_only():
    """The discovery script must be read-only and contain no live execution or secret access."""
    text = SCRIPT.read_text(encoding="utf-8")

    # Critical executable risks
    assert "load_dotenv" not in text
    assert "dotenv" not in text.lower()

    # The script must advertise its read-only nature
    assert "read-only" in text.lower()
    assert "ADVISORY ONLY" in text
    assert "no broker API calls" in text.lower() or "no live" in text.lower()

    # Sanity: it must mention the key safe seam we identified
    assert "position_manager.py" in text and "get_order_status" in text
