#!/usr/bin/env python3
"""CLI for Shadow Prospective Diagnostics."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from shadow_learner.prospective_diagnostics import ProspectiveAnalyzer, PROSPECTIVE_RANDOM_BASELINE


def _fmt(value: Any, digits: int = 3) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def build_markdown_report(results: dict[str, Any], filters: dict[str, Any]) -> str:
    lines = [
        "# Shadow Prospective Diagnostics Report",
        "",
        "> **ADVISORY ONLY**: This report contains shadow-mode diagnostics only. "
        "These metrics do not authorize live trading, scaling, or any change to "
        "production risk parameters.",
        "",
        "## Filters",
        f"- Since: {filters.get('since') or 'all'}",
        f"- Symbol: {filters.get('symbol') or 'all'}",
        f"- Model: {filters.get('model') or 'all'}",
        "",
        "## Summary Metrics",
        f"- Total prospective samples: {results['sample_count']}",
        f"- Labeled outcomes: {results.get('labeled_count', 0)}",
        f"- Average Brier Delta vs Random: {_fmt(results.get('avg_brier_delta'))}",
        f"- Average Accuracy Delta vs Random: {_fmt(results.get('avg_acc_delta'))}",
        f"- Low-confidence prediction share: {_fmt(results.get('low_conf_share'))}",
        f"- T0 feature capture audit failures: {results.get('audit_failures', 0)}",
        "",
        "## Calibration Buckets",
        "| bucket | count | actual up pct | avg confidence |",
        "|---|---:|---:|---:|",
    ]
    for row in results.get("calibration_stats", []):
        lines.append(
            f"| {row['bucket']} | {row['count']} | "
            f"{_fmt(row['actual_up_pct'])} | {_fmt(row['avg_conf'])} |"
        )

    lines.extend([
        "",
        "## Performance by Model/Symbol/Horizon (MSH)",
    ])
    msh_metrics = results.get("msh_metrics", {})
    if msh_metrics:
        lines.append("| Model | Symbol | Horizon | Count | Accuracy | Brier | Actual Up % | Predicted Up % |")
        lines.append("|---|---|---:|---:|---:|---:|---:|---:|")
        for key, m in sorted(msh_metrics.items()):
            lines.append(
                f"| {key[0]} | {key[1]} | {key[2]}m | {m['sample_count']} | "
                f"{_fmt(m['accuracy'])} | {_fmt(m['brier'])} | "
                f"{_fmt(m['actual_up_pct'])} | {_fmt(m['predicted_up_pct'])} |"
            )
    else:
        lines.append("No MSH metrics available.")

    lines.extend([
        "",
        "## Strongest and Weakest Buckets",
    ])
    if results.get("strongest_msh"):
        key, m = results["strongest_msh"]
        lines.append(f"- **Strongest**: {key[0]} | {key[1]} | {key[2]}m (Accuracy: {_fmt(m['accuracy'])})")
    if results.get("weakest_msh"):
        key, m = results["weakest_msh"]
        lines.append(f"- **Weakest**: {key[0]} | {key[1]} | {key[2]}m (Accuracy: {_fmt(m['accuracy'])})")

    lines.extend([
        "",
        "## Final Diagnostic Conclusion",
        "",
        f"**{results['conclusion']}**",
        "",
        "---",
        "Report generated by Shadow Prospective Diagnostics tool.",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--since", help="UTC date or timestamp lower bound")
    parser.add_argument("--symbol", help="Optional symbol filter")
    parser.add_argument("--model", help="Optional model_name filter")
    parser.add_argument("--output", help="Optional markdown report output path")
    parser.add_argument("--db", help="Optional shadow learner SQLite path")
    args = parser.parse_args()

    analyzer = ProspectiveAnalyzer(db_path=args.db)
    rows = analyzer.fetch_data(since=args.since, symbol=args.symbol, model_name=args.model)
    results = analyzer.run_diagnostics(rows)

    filters = {"since": args.since, "symbol": args.symbol, "model": args.model}
    report_md = build_markdown_report(results, filters)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report_md + "\n", encoding="utf-8")
        print(f"Wrote prospective diagnostic report: {output_path}")
    else:
        print(report_md)

    return 0


if __name__ == "__main__":
    sys.exit(main())
